std_msgs/String[] device_names
std_msgs/String[] config_par_names

std_msgs/Int32[] config_par_types  # -> da yaml?
int32 DOUBLE=1
int32 INT16=2

std_msgs/Float64[] config_par_double_values
std_msgs/Int64[] config_par_integer_values

---
std_msgs/Bool result
std_msgs/String result_str